vim.opt.swapfile = false       -- Disable swap file
vim.opt.backup = false         -- Disable backup
vim.opt.writebackup = false    -- Disable write backup
vim.opt.undofile = false       -- Disable persistent undo
vim.opt.lazyredraw = true      -- Don't redraw screen during macros
vim.opt.synmaxcol = 200        -- Only highlight first 200 columns
vim.opt.syntax = "off"         -- Disable syntax highlighting
vim.opt.filetype = "off"       -- Disable filetype detection
vim.opt.number = false         -- Disable line numbers
vim.opt.relativenumber = false -- Disable relative line numbers
vim.opt.foldmethod = "manual"  -- Disable automatic folding
vim.opt.spell = false          -- Disable spell check
vim.opt.ruler = false          -- Disable ruler
vim.opt.showcmd = false        -- Don't show command in status line
vim.opt.wrap = false           -- Don't wrap lines
vim.opt.cursorline = false     -- Don't highlight current line
vim.opt.signcolumn = "no"      -- Hide the sign column
vim.g.loaded_matchparen = 1    -- Disable matching parentheses highlighting
vim.g.loaded_gzip = 1          -- Disable gzip plugin
vim.g.loaded_tarPlugin = 1     -- Disable tar plugin
vim.g.loaded_zipPlugin = 1     -- Disable zip plugin
vim.g.loaded_matchit = 1       -- Disable extended matching
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.loaded_remote_plugins = 1
vim.opt.diffopt = { "filler", "context:3", "iwhite", "internal", "algorithm:patience", "linematch:60" }
