-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "catppuccin"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@class", { fg = "#c1ab5a" })
hi(0, "@constant", { fg = "#cda0e8" })
hi(0, "@constant.builtin", { fg = "#cda0e8" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#a6c291" })
hi(0, "@constructor.lua", { fg = "#e6bed6" })
hi(0, "@constructor.tsx", { fg = "#ddbb8a" })
hi(0, "@constructor.typescript", { fg = "#ddbb8a" })
hi(0, "@decorator", { fg = "#e6bed6" })
hi(0, "@enum", { fg = "#85c8b6" })
hi(0, "@enumMember", { fg = "#e6bed6" })
hi(0, "@error", { link = "Error" })
hi(0, "@event", { fg = "#e6bed6" })
hi(0, "@exception", { fg = "#ec9d73" })
hi(0, "@field", { fg = "#ddbb8a" })
hi(0, "@field.yaml", { fg = "#c1ab5a" })
hi(0, "@float", { link = "Number" })
hi(0, "@function.builtin", { fg = "#cda0e8" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { fg = "#85c8b6" })
hi(0, "@interface", { fg = "#e6bed6" })
hi(0, "@keyword.export", { bold = true, fg = "#abd1b2" })
hi(0, "@keyword.function", { fg = "#ec9d73" })
hi(0, "@keyword.operator", { fg = "#ec9d73" })
hi(0, "@keyword.return", { fg = "#ec9d73" })
hi(0, "@label.json", { fg = "#c1ab5a" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", { link = "@comment", italic = false })
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.function", { link = "Function" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "Function" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
hi(0, "@lsp.type.variable", { fg = "#e78284" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@method", { fg = "#cda0e8" })
hi(0, "@method.call", { link = "@method" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@modifier", { fg = "#e6bed6" })
hi(0, "@namespace", { fg = "#ddbb8a", italic = true })
hi(0, "@number.css", { fg = "#cda0e8" })
hi(0, "@parameter", { fg = "#de9ac3", italic = true })
hi(0, "@property", { fg = "#ddbb8a" })
hi(0, "@property.class.css", { fg = "#bec8ff" })
hi(0, "@property.cpp", { fg = "#ead5e8" })
hi(0, "@property.css", { fg = "#ddbb8a" })
hi(0, "@property.id.css", { fg = "#c1ab5a" })
hi(0, "@property.toml", { fg = "#c1ab5a" })
hi(0, "@punctuation.bracket", { fg = "#aa9c7d" })
hi(0, "@punctuation.delimiter", { fg = "#aa9c7d" })
hi(0, "@punctuation.special", { fg = "#abd1b2" })
hi(0, "@regexp", { fg = "#ffb7b2" })
hi(0, "@string.escape", { fg = "#ffb7b2" })
hi(0, "@string.plain.css", { fg = "#cda0e8" })
hi(0, "@string.regex", { fg = "#cda0e8" })
hi(0, "@string.special", { fg = "#c1ab5a" })
hi(0, "@struct", { fg = "#c1ab5a" })
hi(0, "@symbol", { fg = "#e6bed6" })
hi(0, "@symbol.ruby", { fg = "#e6bed6" })
hi(0, "@tag", { fg = "#ec9d73" })
hi(0, "@tag.attribute", { fg = "#85c8b6", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#ec9d73", italic = true })
hi(0, "@tag.delimiter", { fg = "#abd1b2" })
hi(0, "@text", { fg = "#e1d0ab" })
hi(0, "@text.danger", { bg = "#d783bb", fg = "#3d3422" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#de9ac3", italic = true })
hi(0, "@text.environment", { fg = "#ffb7b2" })
hi(0, "@text.environment.name", { fg = "#c1ab5a" })
hi(0, "@text.literal", { fg = "#85c8b6" })
hi(0, "@text.math", { fg = "#c1ab5a" })
hi(0, "@text.note", { bg = "#c1ab5a", fg = "#3d3422" })
hi(0, "@text.reference", { bold = true, fg = "#ddbb8a" })
hi(0, "@text.strike", { fg = "#e1d0ab", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#de9ac3" })
hi(0, "@text.title", { bold = true, fg = "#c1ab5a" })
hi(0, "@text.todo", { bg = "#bec8ff", fg = "#3d3422" })
hi(0, "@text.todo.checked", { fg = "#6ed0f7" })
hi(0, "@text.todo.unchecked", { fg = "#978b6f" })
hi(0, "@text.underline", { link = "Underline" })
hi(0, "@text.uri", { fg = "#ead5e8", italic = true, underline = true })
hi(0, "@text.warning", { bg = "#bec8ff", fg = "#3d3422" })
hi(0, "@type.builtin", { fg = "#bec8ff" })
hi(0, "@type.css", { fg = "#ddbb8a" })
hi(0, "@type.definition", { link = "@type" })
hi(0, "@type.qualifier", { link = "@type" })
hi(0, "@type.qualifier.php", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#ec9d73" })
hi(0, "@typeParameter", { fg = "#bec8ff" })
hi(0, "@variable", { fg = "#e1d0ab" })
hi(0, "@variable.builtin", { fg = "#d783bb" })
hi(0, "Beacon", { bg = "#c1ab5a" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#cda0e8" })
hi(0, "BufferLineBackground", { bg = "#2d271a", fg = "#86795e" })
hi(0, "BufferLineBuffer", { bg = "#2d271a", fg = "#86795e" })
hi(0, "BufferLineBufferSelected", { bg = "#3d3422", bold = true, fg = "#e1d0ab", italic = true })
hi(0, "BufferLineBufferVisible", { bg = "#382f1e", fg = "#86795e" })
hi(0, "BufferLineCloseButton", { bg = "#2d271a", fg = "#86795e" })
hi(0, "BufferLineCloseButtonSelected", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "BufferLineCloseButtonVisible", { bg = "#382f1e", fg = "#86795e" })
hi(0, "BufferLineDevIconLua", { bg = "#2d271a", fg = "#8ba156" })
hi(0, "BufferLineDevIconLuaSelected", { bg = "#3d3422", fg = "#8ba156" })
hi(0, "BufferLineDevIconSvelteSelected", { bg = "#3d3422", fg = "#d44cdb" })
hi(0, "BufferLineDiagnostic", { bg = "#2d271a", fg = "#655a45" })
hi(0, "BufferLineDiagnosticSelected", { bg = "#3d3422", bold = true, fg = "#a89c81", italic = true })
hi(0, "BufferLineDiagnosticVisible", { bg = "#382f1e", fg = "#655a45" })
hi(0, "BufferLineDuplicate", { bg = "#2d271a", fg = "#7f7259", italic = true })
hi(0, "BufferLineDuplicateSelected", { bg = "#3d3422", fg = "#7f7259", italic = true })
hi(0, "BufferLineDuplicateVisible", { bg = "#382f1e", fg = "#7f7259", italic = true })
hi(0, "BufferLineError", { bg = "#2d271a", fg = "#86795e", sp = "#d783bb" })
hi(0, "BufferLineErrorDiagnostic", { bg = "#2d271a", fg = "#655a45", sp = "#a2628c" })
hi(
	0,
	"BufferLineErrorDiagnosticSelected",
	{ bg = "#3d3422", bold = true, fg = "#a2628c", italic = true, sp = "#a2628c" }
)
hi(0, "BufferLineErrorDiagnosticVisible", { bg = "#382f1e", fg = "#655a45" })
hi(0, "BufferLineErrorSelected", { bg = "#3d3422", bold = true, fg = "#d783bb", italic = true, sp = "#d783bb" })
hi(0, "BufferLineErrorVisible", { bg = "#382f1e", fg = "#86795e" })
hi(0, "BufferLineFill", { bg = "#211c12", fg = "#86795e" })
hi(0, "BufferLineGroupLabel", { bg = "#86795e", fg = "#211c12" })
hi(0, "BufferLineGroupSeparator", { bg = "#211c12", fg = "#86795e" })
hi(0, "BufferLineHint", { bg = "#2d271a", fg = "#86795e", sp = "#85c8b6" })
hi(0, "BufferLineHintDiagnostic", { bg = "#2d271a", fg = "#655a45", sp = "#639689" })
hi(
	0,
	"BufferLineHintDiagnosticSelected",
	{ bg = "#3d3422", bold = true, fg = "#639689", italic = true, sp = "#639689" }
)
hi(0, "BufferLineHintDiagnosticVisible", { bg = "#382f1e", fg = "#655a45" })
hi(0, "BufferLineHintSelected", { bg = "#3d3422", bold = true, fg = "#85c8b6", italic = true, sp = "#85c8b6" })
hi(0, "BufferLineHintVisible", { bg = "#382f1e", fg = "#86795e" })
hi(0, "BufferLineIndicatorSelected", { bg = "#3d3422", fg = "#615741" })
hi(0, "BufferLineIndicatorVisible", { bg = "#382f1e", fg = "#382f1e" })
hi(0, "BufferLineInfo", { bg = "#2d271a", fg = "#86795e", sp = "#abd1b2" })
hi(0, "BufferLineInfoDiagnostic", { bg = "#2d271a", fg = "#655a45", sp = "#809c84" })
hi(
	0,
	"BufferLineInfoDiagnosticSelected",
	{ bg = "#3d3422", bold = true, fg = "#809c84", italic = true, sp = "#809c84" }
)
hi(0, "BufferLineInfoDiagnosticVisible", { bg = "#382f1e", fg = "#655a45" })
hi(0, "BufferLineInfoSelected", { bg = "#3d3422", bold = true, fg = "#abd1b2", italic = true, sp = "#abd1b2" })
hi(0, "BufferLineInfoVisible", { bg = "#382f1e", fg = "#86795e" })
hi(0, "BufferLineModified", { bg = "#2d271a", fg = "#6ed0f7" })
hi(0, "BufferLineModifiedSelected", { bg = "#3d3422", fg = "#6ed0f7" })
hi(0, "BufferLineModifiedVisible", { bg = "#382f1e", fg = "#6ed0f7" })
hi(0, "BufferLineNumbers", { bg = "#2d271a", fg = "#86795e" })
hi(0, "BufferLineNumbersSelected", { bg = "#3d3422", bold = true, fg = "#e1d0ab", italic = true })
hi(0, "BufferLineNumbersVisible", { bg = "#382f1e", fg = "#86795e" })
hi(0, "BufferLineOffsetSeparator", { bg = "#211c12", fg = "#2d2618" })
hi(0, "BufferLinePick", { bg = "#2d271a", bold = true, fg = "#d783bb", italic = true })
hi(0, "BufferLinePickSelected", { bg = "#3d3422", bold = true, fg = "#d783bb", italic = true })
hi(0, "BufferLinePickVisible", { bg = "#382f1e", bold = true, fg = "#d783bb", italic = true })
hi(0, "BufferLineSeparator", { bg = "#2d271a", fg = "#211c12" })
hi(0, "BufferLineSeparatorSelected", { bg = "#3d3422", fg = "#211c12" })
hi(0, "BufferLineSeparatorVisible", { bg = "#382f1e", fg = "#211c12" })
hi(0, "BufferLineTab", { bg = "#2d271a", fg = "#86795e" })
hi(0, "BufferLineTabClose", { bg = "#2d271a", fg = "#86795e" })
hi(0, "BufferLineTabSelected", { bg = "#3d3422", fg = "#615741" })
hi(0, "BufferLineTabSeparator", { bg = "#2d271a", fg = "#211c12" })
hi(0, "BufferLineTabSeparatorSelected", { bg = "#3d3422", fg = "#211c12" })
hi(0, "BufferLineWarning", { bg = "#2d271a", fg = "#86795e", sp = "#bec8ff" })
hi(0, "BufferLineWarningDiagnostic", { bg = "#2d271a", fg = "#655a45", sp = "#8e96c0" })
hi(
	0,
	"BufferLineWarningDiagnosticSelected",
	{ bg = "#3d3422", bold = true, fg = "#8e96c0", italic = true, sp = "#8e96c0" }
)
hi(0, "BufferLineWarningDiagnosticVisible", { bg = "#382f1e", fg = "#655a45" })
hi(0, "BufferLineWarningSelected", { bg = "#3d3422", bold = true, fg = "#bec8ff", italic = true, sp = "#bec8ff" })
hi(0, "BufferLineWarningVisible", { bg = "#382f1e", fg = "#86795e" })
hi(0, "Character", { fg = "#85c8b6" })
hi(0, "CmpItemAbbr", { fg = "#aa9c7d" })
hi(0, "CmpItemAbbrDefault", { fg = "#aa9c7d" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#86795e", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#86795e" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e1d0ab" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#aa9c7d" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e1d0ab" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#aa9c7d" })
hi(0, "CmpItemKind", { fg = "#c1ab5a" })
hi(0, "CmpItemKindClass", { fg = "#bec8ff" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#d783bb" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#cda0e8" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#c1ab5a" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#85c8b6" })
hi(0, "CmpItemKindDefault", { fg = "#ffb7b2" })
hi(0, "CmpItemKindEnum", { fg = "#6ed0f7" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#d783bb" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#c1ab5a" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#6ed0f7" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#c1ab5a" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#c1ab5a" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#c1ab5a" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#bec8ff" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#d783bb" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#c1ab5a" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#c1ab5a" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#c1ab5a" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#6ed0f7" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#d783bb" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#ec9d73" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#c1ab5a" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#85c8b6" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#c1ab5a" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#6ed0f7" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#cda0e8" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#e6bed6" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#e1d0ab" })
hi(0, "CmpItemMenuDefault", { fg = "#aa9c7d" })
hi(0, "ColInLineDiagnostic", { fg = "#86795e", italic = true })
hi(0, "ColorColumn", { bg = "#4f4531" })
hi(0, "Comment", { fg = "#86795e", italic = true })
hi(0, "Conceal", { fg = "#978b6f" })
hi(0, "Conditional", { fg = "#ec9d73", italic = true })
hi(0, "Constant", { fg = "#cda0e8" })
hi(0, "CurSearch", { bg = "#d783bb", fg = "#342c1c" })
hi(0, "Cursor", { bg = "#e1d0ab", fg = "#3d3422" })
hi(0, "CursorColumn", { bg = "#342c1c" })
hi(0, "CursorIM", { bg = "#e1d0ab", fg = "#3d3422" })
hi(0, "CursorLine", { bg = "#483f2c" })
hi(0, "CursorLineNr", { fg = "#ddbb8a" })
hi(0, "DashboardCenter", { fg = "#6ed0f7" })
hi(0, "DashboardFooter", { fg = "#bec8ff", italic = true })
hi(0, "DashboardHeader", { fg = "#c1ab5a" })
hi(0, "DashboardShortCut", { fg = "#ffb7b2" })
hi(0, "DefinitionArrow", { fg = "#a74877" })
hi(0, "DefinitionBorder", { fg = "#c7debd" })
hi(0, "DefinitionCount", { bold = true, fg = "#c1ab5a" })
hi(0, "DefinitionFile", { bg = "#261a00" })
hi(0, "DefinitionSearch", { bg = "#5f634d", fg = "#e1d0ab" })
hi(0, "Definitions", { bold = true, fg = "#f4a56d" })
hi(0, "DefinitionsIcon", { fg = "#bddeff" })
hi(0, "DiagnosticDeprecated", { sp = "#d82dce", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#d783bb", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#d783bb" })
hi(0, "DiagnosticFloatingHint", { fg = "#85c8b6" })
hi(0, "DiagnosticFloatingInfo", { fg = "#abd1b2" })
hi(0, "DiagnosticFloatingWarn", { fg = "#bec8ff" })
hi(0, "DiagnosticHint", { fg = "#85c8b6", italic = true })
hi(0, "DiagnosticInfo", { fg = "#abd1b2", italic = true })
hi(0, "DiagnosticLineCol", { fg = "#777972" })
hi(0, "DiagnosticMap", { fg = "#eb7d67" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#7ae5ff" })
hi(0, "DiagnosticQuickFix", { bold = true, fg = "#00c6e8" })
hi(0, "DiagnosticSignError", { fg = "#d783bb" })
hi(0, "DiagnosticSignHint", { fg = "#85c8b6" })
hi(0, "DiagnosticSignInfo", { fg = "#abd1b2" })
hi(0, "DiagnosticSignWarn", { fg = "#bec8ff" })
hi(0, "DiagnosticUnderlineError", { sp = "#d783bb", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#85c8b6", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#abd1b2", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#7ae5ff", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#bec8ff", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#4b3b2f", fg = "#d783bb", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#444230", fg = "#85c8b6", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#474330", fg = "#abd1b2", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#484238", fg = "#bec8ff", italic = true })
hi(0, "DiagnosticWarn", { fg = "#bec8ff", italic = true })
hi(0, "DiffAdd", { bg = "#48504a" })
hi(0, "DiffChange", { bg = "#463c25" })
hi(0, "DiffDelete", { bg = "#58423d" })
hi(0, "DiffText", { bg = "#55492c" })
hi(0, "Directory", { fg = "#c1ab5a" })
hi(0, "EndOfBuffer", { fg = "#3d3422" })
hi(0, "Error", { fg = "#d783bb" })
hi(0, "ErrorMsg", { bold = true, fg = "#d783bb", italic = true })
hi(0, "FinderParam", { bg = "#4d2905", bold = true, fg = "#f4a56d" })
hi(0, "FinderPreviewSearch", { bg = "#5f634d", fg = "#e1d0ab" })
hi(0, "FinderSpinner", { bold = true, fg = "#ba2d58" })
hi(0, "FinderSpinnerBorder", { fg = "#9eb14c" })
hi(0, "FinderSpinnerTitle", { bold = true, fg = "#ba2d58" })
hi(0, "FinderVirtText", { fg = "#ad5dae" })
hi(0, "Float", { fg = "#cda0e8" })
hi(0, "FloatBorder", { fg = "#c1ab5a" })
hi(0, "FocusedSymbol", { fg = "#bec8ff" })
hi(0, "FoldColumn", { fg = "#86795e" })
hi(0, "Folded", { bg = "#615741", fg = "#c1ab5a" })
hi(0, "Function", { fg = "#c1ab5a" })
hi(0, "GitSignsAdd", { fg = "#6ed0f7" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#48504a" })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddLnVirtLn", { bg = "#48504a" })
hi(0, "GitSignsAddLnVirtLnInLine", { reverse = true })
hi(0, "GitSignsAddNr", { fg = "#6ed0f7" })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = "#bec8ff" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#463c25" })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { fg = "#bec8ff" })
hi(0, "GitSignsChangeVirtLn", { bg = "#463c25" })
hi(0, "GitSignsChangeVirtLnInLine", { reverse = true })
hi(0, "GitSignsCurrentLineBlame", { fg = "#86795e" })
hi(0, "GitSignsDelete", { fg = "#d783bb" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { fg = "#d783bb" })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#58423d" })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GlyphPalette1", { fg = "#d783bb" })
hi(0, "GlyphPalette2", { fg = "#85c8b6" })
hi(0, "GlyphPalette3", { fg = "#bec8ff" })
hi(0, "GlyphPalette4", { fg = "#c1ab5a" })
hi(0, "GlyphPalette6", { fg = "#85c8b6" })
hi(0, "GlyphPalette7", { fg = "#e1d0ab" })
hi(0, "GlyphPalette9", { fg = "#d783bb" })
hi(0, "HopNextKey", { bold = true, ctermfg = 198, fg = "#fa0f92" })
hi(0, "HopNextKey1", { bold = true, ctermfg = 45, fg = "#82e18f" })
hi(0, "HopNextKey2", { ctermfg = 33, fg = "#6b8e4a" })
hi(0, "HopPreview", { bold = true, ctermfg = 142, fg = "#6db8ff" })
hi(0, "HopUnmatched", { bg = "#3d3422", ctermfg = 242, fg = "#666666", sp = "#666666" })
hi(0, "Identifier", { fg = "#e6bed6" })
hi(0, "Implements", { bold = true, fg = "#f4a56d" })
hi(0, "ImplementsCount", { bold = true, fg = "#c1ab5a" })
hi(0, "ImplementsIcon", { fg = "#bddeff" })
hi(0, "IncSearch", { bg = "#a1c1a3", fg = "#342c1c" })
hi(0, "Include", { fg = "#ec9d73" })
hi(0, "IndentBlanklineChar", { fg = "#4f4531" })
hi(0, "IndentBlanklineContextChar", { fg = "#e1d0ab" })
hi(0, "IndentBlanklineContextStart", { sp = "#e1d0ab", underline = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#ec9d73" })
hi(0, "LSOutlinePreviewBorder", { fg = "#01aabc" })
hi(0, "Label", { fg = "#a6c291" })
hi(0, "LineNr", { fg = "#615741" })
hi(0, "LspCodeLens", { fg = "#86795e" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#d783bb" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#85c8b6" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#abd1b2" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#bec8ff" })
hi(0, "LspDiagnosticsError", { fg = "#d783bb" })
hi(0, "LspDiagnosticsHint", { fg = "#85c8b6" })
hi(0, "LspDiagnosticsInformation", { fg = "#abd1b2" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#d783bb", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#85c8b6", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#abd1b2", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#bec8ff", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#d783bb", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#85c8b6", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#abd1b2", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#bec8ff", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#bec8ff" })
hi(0, "LspFloatWinNormal", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "LspInfoBorder", { fg = "#c1ab5a" })
hi(0, "LspInfoFiletype", { fg = "#bec8ff" })
hi(0, "LspInfoList", { fg = "#c1ab5a" })
hi(0, "LspInfoTip", { fg = "#86795e", italic = true })
hi(0, "LspInfoTitle", { bold = true, fg = "#c1ab5a" })
hi(0, "LspInlayHint", { fg = "#c1ab5a" })
hi(0, "LspReferenceRead", { bg = "#615741" })
hi(0, "LspReferenceText", { bg = "#615741" })
hi(0, "LspReferenceWrite", { bg = "#615741" })
hi(0, "LspSagaAutoPreview", { fg = "#9eb14c" })
hi(0, "LspSagaBorderTitle", { fg = "#6ed0f7" })
hi(0, "LspSagaCodeActionBorder", { fg = "#f4a56d" })
hi(0, "LspSagaCodeActionContent", { bold = true, fg = "#4dbcf0" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#b087dd" })
hi(0, "LspSagaCodeActionTrunCateLine", { fg = "#f4a56d" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#f4a56d" })
hi(0, "LspSagaDiagnosticError", { fg = "#d783bb", italic = true })
hi(0, "LspSagaDiagnosticHeader", { fg = "#7fceff" })
hi(0, "LspSagaDiagnosticHint", { fg = "#85c8b6", italic = true })
hi(0, "LspSagaDiagnosticInfo", { fg = "#abd1b2", italic = true })
hi(0, "LspSagaDiagnosticSource", { fg = "#86795e", italic = true })
hi(0, "LspSagaDiagnosticTruncateLine", { fg = "#f4a56d" })
hi(0, "LspSagaDiagnosticWarn", { fg = "#bec8ff", italic = true })
hi(0, "LspSagaErrorTrunCateLine", { fg = "#d783bb", italic = true })
hi(0, "LspSagaFinderSelection", { bold = true, fg = "#48d1ff" })
hi(0, "LspSagaHintTrunCateLine", { fg = "#85c8b6", italic = true })
hi(0, "LspSagaHoverBorder", { fg = "#b7c0ff" })
hi(0, "LspSagaHoverTrunCateLine", { fg = "#b7c0ff" })
hi(0, "LspSagaInfoTrunCateLine", { fg = "#abd1b2", italic = true })
hi(0, "LspSagaLightBulb", { fg = "#85c8b6" })
hi(0, "LspSagaLspFinderBorder", { fg = "#9eb14c" })
hi(0, "LspSagaRenameBorder", { fg = "#6ab784" })
hi(0, "LspSagaRenameMatch", { bg = "#5f634d", fg = "#e1d0ab" })
hi(0, "LspSagaShTrunCateLine", { fg = "#4dbcf0" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#4dbcf0" })
hi(0, "LspSagaWarnTrunCateLine", { fg = "#bec8ff", italic = true })
hi(0, "LspSagaWinbarArray", { fg = "#a6b151" })
hi(0, "LspSagaWinbarBoolean", { fg = "#c48cff" })
hi(0, "LspSagaWinbarClass", { fg = "#f4a56d" })
hi(0, "LspSagaWinbarConstant", { fg = "#74d196" })
hi(0, "LspSagaWinbarConstructor", { fg = "#a6b151" })
hi(0, "LspSagaWinbarEnum", { fg = "#7fceff" })
hi(0, "LspSagaWinbarEnumMember", { fg = "#7fceff" })
hi(0, "LspSagaWinbarEvent", { fg = "#f4a56d" })
hi(0, "LspSagaWinbarField", { fg = "#00bbad" })
hi(0, "LspSagaWinbarFile", { bold = true, fg = "#c5c2b4" })
hi(0, "LspSagaWinbarFunction", { fg = "#f4a56d" })
hi(0, "LspSagaWinbarInterface", { fg = "#c48cff" })
hi(0, "LspSagaWinbarKey", { fg = "#df59a0" })
hi(0, "LspSagaWinbarMacro", { fg = "#df59a0" })
hi(0, "LspSagaWinbarMethod", { fg = "#f4a56d" })
hi(0, "LspSagaWinbarModule", { fg = "#a6b151" })
hi(0, "LspSagaWinbarNamespace", { fg = "#c48cff" })
hi(0, "LspSagaWinbarNull", { fg = "#df59a0" })
hi(0, "LspSagaWinbarNumber", { fg = "#7fceff" })
hi(0, "LspSagaWinbarObject", { fg = "#c48cff" })
hi(0, "LspSagaWinbarOperator", { fg = "#7fceff" })
hi(0, "LspSagaWinbarPackage", { fg = "#f4a56d" })
hi(0, "LspSagaWinbarParameter", { fg = "#a6b151" })
hi(0, "LspSagaWinbarProperty", { fg = "#74d196" })
hi(0, "LspSagaWinbarSep", { fg = "#d96c81" })
hi(0, "LspSagaWinbarStaticMethod", { fg = "#c48cff" })
hi(0, "LspSagaWinbarString", { fg = "#7fceff" })
hi(0, "LspSagaWinbarStruct", { fg = "#f4a56d" })
hi(0, "LspSagaWinbarTypeAlias", { fg = "#7fceff" })
hi(0, "LspSagaWinbarTypeParameter", { fg = "#7fceff" })
hi(0, "LspSagaWinbarVariable", { fg = "#a6b151" })
hi(0, "LspSignatureActiveParameter", { fg = "#cda0e8" })
hi(0, "Macro", { fg = "#ec9d73" })
hi(0, "MatchParen", { bg = "#615741", bold = true, fg = "#cda0e8" })
hi(0, "ModeMsg", { bold = true, fg = "#e1d0ab" })
hi(0, "MoreMsg", { fg = "#c1ab5a" })
hi(0, "MsgSeparator", {})
hi(0, "NoiceCmdline", {})
hi(0, "NoiceCmdlineIcon", { fg = "#abd1b2" })
hi(0, "NoiceCmdlineIconCalculator", { fg = "#abd1b2" })
hi(0, "NoiceCmdlineIconCmdline", { fg = "#abd1b2" })
hi(0, "NoiceCmdlineIconFilter", { fg = "#abd1b2" })
hi(0, "NoiceCmdlineIconHelp", { fg = "#abd1b2" })
hi(0, "NoiceCmdlineIconInput", { fg = "#abd1b2" })
hi(0, "NoiceCmdlineIconLua", { fg = "#abd1b2" })
hi(0, "NoiceCmdlineIconSearch", { fg = "#bec8ff" })
hi(0, "NoiceCmdlinePopup", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#abd1b2" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#abd1b2" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#abd1b2" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#abd1b2" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#abd1b2" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#abd1b2" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#abd1b2" })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = "#bec8ff" })
hi(0, "NoiceCmdlinePrompt", { bold = true, fg = "#c1ab5a" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindColor", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindField", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindFile", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindFolder", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindText", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#ffb7b2" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#ffb7b2" })
hi(0, "NoiceConfirm", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "NoiceConfirmBorder", { fg = "#abd1b2" })
hi(0, "NoiceCursor", { bg = "#e1d0ab", fg = "#3d3422" })
hi(0, "NoiceFormatConfirm", { bg = "#483f2c" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#615741", bold = true })
hi(0, "NoiceFormatDate", { fg = "#ffb7b2" })
hi(0, "NoiceFormatEvent", { fg = "#86795e" })
hi(0, "NoiceFormatKind", { fg = "#86795e" })
hi(0, "NoiceFormatLevelDebug", { fg = "#86795e" })
hi(0, "NoiceFormatLevelError", { bg = "#4b3b2f", fg = "#d783bb", italic = true })
hi(0, "NoiceFormatLevelInfo", { bg = "#474330", fg = "#abd1b2", italic = true })
hi(0, "NoiceFormatLevelOff", { fg = "#86795e" })
hi(0, "NoiceFormatLevelTrace", { fg = "#86795e" })
hi(0, "NoiceFormatLevelWarn", { bg = "#484238", fg = "#bec8ff", italic = true })
hi(0, "NoiceFormatProgressDone", { bg = "#5f634d", fg = "#e1d0ab" })
hi(0, "NoiceFormatProgressTodo", { bg = "#483f2c" })
hi(0, "NoiceFormatTitle", { bold = true, fg = "#c1ab5a" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { bold = true, fg = "#c1ab5a" })
hi(0, "NoiceLspProgressSpinner", { fg = "#cda0e8" })
hi(0, "NoiceLspProgressTitle", { fg = "#86795e" })
hi(0, "NoiceMini", {})
hi(0, "NoicePopup", { bg = "#342c1c", fg = "#e1d0ab" })
hi(0, "NoicePopupBorder", { fg = "#c1ab5a" })
hi(0, "NoicePopupmenu", { bg = "#483f2c", fg = "#aa9c7d" })
hi(0, "NoicePopupmenuBorder", { fg = "#c1ab5a" })
hi(0, "NoicePopupmenuMatch", { fg = "#ffb7b2" })
hi(0, "NoicePopupmenuSelected", { bg = "#615741", bold = true, fg = "#e1d0ab" })
hi(0, "NoiceScrollbar", { bg = "#615741" })
hi(0, "NoiceScrollbarThumb", { bg = "#86795e" })
hi(0, "NoiceSplit", { bg = "#342c1c", fg = "#e1d0ab" })
hi(0, "NoiceSplitBorder", { fg = "#c1ab5a" })
hi(0, "NoiceVirtualText", { bg = "#474330", fg = "#abd1b2", italic = true })
hi(0, "NonText", { fg = "#86795e" })
hi(0, "Normal", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "NormalFloat", { bg = "#342c1c", fg = "#e1d0ab" })
hi(0, "NormalNC", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "NormalSB", { bg = "#2d2618", fg = "#e1d0ab" })
hi(0, "NotifyDEBUGBorder", { fg = "#cda0e8" })
hi(0, "NotifyDEBUGIcon", { fg = "#cda0e8" })
hi(0, "NotifyDEBUGTitle", { fg = "#cda0e8", italic = true })
hi(0, "NotifyERRORBorder", { fg = "#d783bb" })
hi(0, "NotifyERRORIcon", { fg = "#d783bb" })
hi(0, "NotifyERRORTitle", { fg = "#d783bb", italic = true })
hi(0, "NotifyINFOBorder", { fg = "#c1ab5a" })
hi(0, "NotifyINFOIcon", { fg = "#c1ab5a" })
hi(0, "NotifyINFOTitle", { fg = "#c1ab5a", italic = true })
hi(0, "NotifyTRACEBorder", { fg = "#ead5e8" })
hi(0, "NotifyTRACEIcon", { fg = "#ead5e8" })
hi(0, "NotifyTRACETitle", { fg = "#ead5e8", italic = true })
hi(0, "NotifyWARNBorder", { fg = "#bec8ff" })
hi(0, "NotifyWARNIcon", { fg = "#bec8ff" })
hi(0, "NotifyWARNTitle", { fg = "#bec8ff", italic = true })
hi(0, "Number", { fg = "#cda0e8" })
hi(0, "NvimInternalError", { bg = "#d82dce", ctermbg = 9, ctermfg = 9, fg = "#d82dce" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#c1ab5a" })
hi(0, "NvimTreeFolderIcon", { fg = "#c1ab5a" })
hi(0, "NvimTreeFolderName", { fg = "#c1ab5a" })
hi(0, "NvimTreeGitDeleted", { fg = "#d783bb" })
hi(0, "NvimTreeGitDirty", { fg = "#bec8ff" })
hi(0, "NvimTreeGitNew", { fg = "#c1ab5a" })
hi(0, "NvimTreeImageFile", { fg = "#e1d0ab" })
hi(0, "NvimTreeIndentMarker", { fg = "#86795e" })
hi(0, "NvimTreeNormal", { bg = "#342c1c", fg = "#e1d0ab" })
hi(0, "NvimTreeOpenedFile", { fg = "#ffb7b2" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#c1ab5a" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#ddbb8a" })
hi(0, "NvimTreeSpecialFile", { fg = "#e6bed6" })
hi(0, "NvimTreeStatuslineNc", { bg = "#342c1c", fg = "#342c1c" })
hi(0, "NvimTreeSymlink", { fg = "#ffb7b2" })
hi(0, "NvimTreeWinSeparator", { bg = "#3d3422", fg = "#3d3422" })
hi(0, "Operator", { fg = "#abd1b2" })
hi(0, "OutlineDetail", { fg = "#777972" })
hi(0, "OutlineFoldPrefix", { fg = "#a54a9e" })
hi(0, "OutlineIndentEvn", { fg = "#e05053" })
hi(0, "OutlineIndentOdd", { fg = "#9474bc" })
hi(0, "Pmenu", { bg = "#483f2c", fg = "#aa9c7d" })
hi(0, "PmenuSbar", { bg = "#615741" })
hi(0, "PmenuSel", { bg = "#615741", bold = true, fg = "#e1d0ab" })
hi(0, "PmenuThumb", { bg = "#86795e" })
hi(0, "PreProc", { fg = "#ffb7b2" })
hi(0, "Question", { fg = "#c1ab5a" })
hi(0, "QuickFixLine", { bg = "#615741", bold = true })
hi(0, "RedrawDebugClear", { bg = "#ecf6ff", ctermbg = 11 })
hi(0, "RedrawDebugComposed", { bg = "#00758c", ctermbg = 10 })
hi(0, "RedrawDebugRecompose", { bg = "#d82dce", ctermbg = 9 })
hi(0, "References", { bold = true, fg = "#f4a56d" })
hi(0, "ReferencesCount", { bold = true, fg = "#c1ab5a" })
hi(0, "ReferencesIcon", { fg = "#bddeff" })
hi(0, "Repeat", { fg = "#ec9d73" })
hi(0, "SagaShadow", { fg = "#000000" })
hi(0, "Search", { bg = "#5f634d", fg = "#e1d0ab" })
hi(0, "SignColumn", { fg = "#615741" })
hi(0, "SignColumnSB", { bg = "#2d2618", fg = "#615741" })
hi(0, "Special", { fg = "#ffb7b2" })
hi(0, "SpecialKey", { fg = "#e1d0ab" })
hi(0, "SpellBad", { sp = "#d783bb", undercurl = true })
hi(0, "SpellCap", { sp = "#bec8ff", undercurl = true })
hi(0, "SpellLocal", { sp = "#c1ab5a", undercurl = true })
hi(0, "SpellRare", { sp = "#6ed0f7", undercurl = true })
hi(0, "Statement", { fg = "#ec9d73" })
hi(0, "StatusLine", { bg = "#342c1c", fg = "#e1d0ab" })
hi(0, "StatusLineNC", { bg = "#342c1c", fg = "#615741" })
hi(0, "StorageClass", { fg = "#bec8ff" })
hi(0, "String", { fg = "#6ed0f7" })
hi(0, "Structure", { fg = "#bec8ff" })
hi(0, "Substitute", { bg = "#615741", fg = "#ffb7b2" })
hi(0, "TSRainbowBlue", { fg = "#c1ab5a" })
hi(0, "TSRainbowCyan", { fg = "#85c8b6" })
hi(0, "TSRainbowGreen", { fg = "#6ed0f7" })
hi(0, "TSRainbowOrange", { fg = "#cda0e8" })
hi(0, "TSRainbowRed", { fg = "#d783bb" })
hi(0, "TSRainbowViolet", { fg = "#ec9d73" })
hi(0, "TSRainbowYellow", { fg = "#bec8ff" })
hi(0, "TabLine", { bg = "#342c1c", fg = "#615741" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#615741", fg = "#6ed0f7" })
hi(0, "TargetFileName", { fg = "#ced4d7" })
hi(0, "TelescopeBorder", { fg = "#c1ab5a" })
hi(0, "TelescopeMatching", { fg = "#c1ab5a" })
hi(0, "TelescopeMultiIcon", { fg = "#e6bed6" })
hi(0, "TelescopeMultiSelection", { fg = "#bec8ff" })
hi(0, "TelescopeNormal", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "TelescopePreviewBlock", { fg = "#cda0e8" })
hi(0, "TelescopePreviewBorder", { fg = "#c1ab5a" })
hi(0, "TelescopePreviewCharDev", { fg = "#cda0e8" })
hi(0, "TelescopePreviewDate", { fg = "#c1ab5a" })
hi(0, "TelescopePreviewDirectory", { fg = "#c1ab5a" })
hi(0, "TelescopePreviewExecute", { fg = "#6ed0f7" })
hi(0, "TelescopePreviewGroup", { fg = "#cda0e8" })
hi(0, "TelescopePreviewHyphen", { fg = "#86795e" })
hi(0, "TelescopePreviewLine", { bg = "#615741", bold = true })
hi(0, "TelescopePreviewLink", { fg = "#ffb7b2" })
hi(0, "TelescopePreviewMatch", { bg = "#5f634d", fg = "#e1d0ab" })
hi(0, "TelescopePreviewMessage", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "TelescopePreviewMessageFillchar", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "TelescopePreviewNormal", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "TelescopePreviewPipe", { fg = "#cda0e8" })
hi(0, "TelescopePreviewRead", { fg = "#cda0e8" })
hi(0, "TelescopePreviewSize", { fg = "#6ed0f7" })
hi(0, "TelescopePreviewSocket", { fg = "#ec9d73" })
hi(0, "TelescopePreviewSticky", { fg = "#ec9d73" })
hi(0, "TelescopePreviewTitle", { fg = "#c1ab5a" })
hi(0, "TelescopePreviewUser", { fg = "#cda0e8" })
hi(0, "TelescopePreviewWrite", { fg = "#ec9d73" })
hi(0, "TelescopePromptBorder", { fg = "#c1ab5a" })
hi(0, "TelescopePromptCounter", { fg = "#86795e" })
hi(0, "TelescopePromptNormal", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "TelescopePromptPrefix", { fg = "#e6bed6" })
hi(0, "TelescopePromptTitle", { fg = "#c1ab5a" })
hi(0, "TelescopeResultsBorder", { fg = "#c1ab5a" })
hi(0, "TelescopeResultsClass", { fg = "#c1ab5a" })
hi(0, "TelescopeResultsComment", { fg = "#86795e", italic = true })
hi(0, "TelescopeResultsConstant", { fg = "#cda0e8" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#48504a" })
hi(0, "TelescopeResultsDiffChange", { bg = "#463c25" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#58423d" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#86795e" })
hi(0, "TelescopeResultsField", { fg = "#c1ab5a" })
hi(0, "TelescopeResultsFunction", { fg = "#c1ab5a" })
hi(0, "TelescopeResultsIdentifier", { fg = "#e6bed6" })
hi(0, "TelescopeResultsLineNr", { fg = "#615741" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "TelescopeResultsNumber", { fg = "#cda0e8" })
hi(0, "TelescopeResultsOperator", { fg = "#abd1b2" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#ffb7b2" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { fg = "#c1ab5a" })
hi(0, "TelescopeResultsVariable", { fg = "#ffb7b2" })
hi(0, "TelescopeSelection", { bg = "#4f4531", bold = true, fg = "#e1d0ab" })
hi(0, "TelescopeSelectionCaret", { fg = "#e6bed6" })
hi(0, "TelescopeTitle", { fg = "#c1ab5a" })
hi(0, "Title", { bold = true, fg = "#c1ab5a" })
hi(0, "Todo", { bg = "#bec8ff", bold = true, fg = "#3d3422" })
hi(0, "Type", { fg = "#bec8ff" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#2d2618" })
hi(0, "VimwikiHR", { fg = "#bec8ff" })
hi(0, "VimwikiHeader1", { bold = true, fg = "#cda0e8" })
hi(0, "VimwikiHeader2", { bold = true, fg = "#6ed0f7" })
hi(0, "VimwikiHeader3", { bold = true, fg = "#c1ab5a" })
hi(0, "VimwikiHeader4", { bold = true, fg = "#abd1b2" })
hi(0, "VimwikiHeader5", { bold = true, fg = "#bec8ff" })
hi(0, "VimwikiHeader6", { bold = true, fg = "#ec9d73" })
hi(0, "VimwikiLink", { fg = "#abd1b2" })
hi(0, "VimwikiList", { fg = "#cda0e8" })
hi(0, "VimwikiMarkers", { fg = "#bdad8c" })
hi(0, "VimwikiTag", { fg = "#cda0e8" })
hi(0, "Visual", { bg = "#615741", bold = true })
hi(0, "VisualNOS", { bg = "#615741", bold = true })
hi(0, "WarningMsg", { fg = "#bec8ff" })
hi(0, "WhichKey", { fg = "#c1ab5a" })
hi(0, "WhichKeyBorder", { fg = "#c1ab5a" })
hi(0, "WhichKeyDesc", { fg = "#e6bed6" })
hi(0, "WhichKeyFloat", { bg = "#342c1c", fg = "#e1d0ab" })
hi(0, "WhichKeyGroup", { fg = "#ec9d73" })
hi(0, "WhichKeySeparator", { fg = "#86795e", italic = true })
hi(0, "WhichKeyValue", { fg = "#86795e", italic = true })
hi(0, "Whitespace", { fg = "#615741" })
hi(0, "WildMenu", { bg = "#86795e" })
hi(0, "WinBar", { fg = "#ead5e8" })
hi(0, "debugBreakpoint", { bg = "#3d3422", fg = "#86795e" })
hi(0, "debugPC", { bg = "#2d2618" })
hi(0, "diffAdded", { fg = "#6ed0f7" })
hi(0, "diffChanged", { fg = "#c1ab5a" })
hi(0, "diffFile", { fg = "#c1ab5a" })
hi(0, "diffIndexLine", { fg = "#85c8b6" })
hi(0, "diffLine", { fg = "#86795e" })
hi(0, "diffNewFile", { fg = "#cda0e8" })
hi(0, "diffOldFile", { fg = "#bec8ff" })
hi(0, "diffRemoved", { fg = "#d783bb" })
hi(0, "healthError", { fg = "#d783bb" })
hi(0, "healthSuccess", { fg = "#85c8b6" })
hi(0, "healthWarning", { fg = "#bec8ff" })
hi(0, "htmlH1", { bold = true, fg = "#ffb7b2" })
hi(0, "htmlH2", { bold = true, fg = "#c1ab5a" })
hi(0, "illuminatedCurWord", { bg = "#615741" })
hi(0, "illuminatedWord", { bg = "#615741" })
hi(0, "lCursor", { bg = "#e1d0ab", fg = "#3d3422" })
hi(0, "markdownCode", { fg = "#e6bed6" })
hi(0, "markdownCodeBlock", { fg = "#e6bed6" })
hi(0, "markdownH1", { fg = "#ddbb8a" })
hi(0, "markdownH2", { fg = "#ec9d73" })
hi(0, "markdownH3", { fg = "#6ed0f7" })
hi(0, "markdownH4", { fg = "#bec8ff" })
hi(0, "markdownH5", { fg = "#ffb7b2" })
hi(0, "markdownH6", { fg = "#85c8b6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#cda0e8" })
hi(0, "markdownLinkText", { fg = "#c1ab5a", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#3d3422", fg = "#e1d0ab" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#e6bed6" })
hi(0, "mkdCodeStart", { bold = true, fg = "#e6bed6" })
hi(0, "qfFileName", { fg = "#c1ab5a" })
hi(0, "qfLineNr", { fg = "#bec8ff" })
hi(0, "tkBrackets", { fg = "#ffb7b2" })
hi(0, "tkLink", { fg = "#c1ab5a" })
hi(0, "tkTag", { fg = "#abd1b2" })

-- No terminal colors defined
